# Generated by Django 2.1.11 on 2019-08-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='topic',
            name='url',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
