# Generated by Django 2.1.11 on 2019-09-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190830_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('QUE', 'Queued'), ('COM', 'Completed'), ('CAN', 'Cancelled')], default='QUE', max_length=3),
        ),
    ]
