# Generated by Django 2.1.11 on 2019-09-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190901_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('QUE', 'Queued'), ('COM', 'Completed'), ('CAN', 'Cancelled'), ('ACT', 'Active')], default='QUE', max_length=3),
        ),
    ]
